#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Build the signed policy tree under build/policies.

Root hashes and digests are generated by earlier build steps.  Source
policies refer to them with named placeholders; this script substitutes
the generated values before signing every policy.
"""

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes as cryptographic_hashes
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.serialization import pkcs7

import hashes
import layout
import signing

HEX_DIGITS = "0123456789abcdef"


def sign(
    *,
    policy: Path,
    output: Path,
    signer: signing.Identity,
    certificates: tuple[Path, ...],
    trusted_certificate: Path,
) -> None:
    """Create an attached CMS signature and verify its embedded policy."""
    key = serialization.load_pem_private_key(signer.key.read_bytes(), password=None)
    if not isinstance(key, rsa.RSAPrivateKey):
        raise TypeError(f"{signer.key} does not contain an RSA private key")
    certificate = x509.load_pem_x509_certificate(signer.certificate.read_bytes())
    signature = (
        pkcs7.PKCS7SignatureBuilder()
        .set_data(policy.read_bytes())
        .add_signer(certificate, key, cryptographic_hashes.SHA256())
    )
    for certificate_path in certificates:
        signature = signature.add_certificate(
            x509.load_pem_x509_certificate(certificate_path.read_bytes())
        )
    output.write_bytes(
        signature.sign(
            serialization.Encoding.DER,
            [pkcs7.PKCS7Options.Binary, pkcs7.PKCS7Options.NoAttributes],
        )
    )

    content = subprocess.run(
        [
            "openssl",
            "cms",
            "-verify",
            "-in",
            output,
            "-inform",
            "DER",
            "-CAfile",
            trusted_certificate,
            "-partial_chain",
            "-purpose",
            "any",
            "-out",
            "/dev/stdout",
        ],
        check=True,
        capture_output=True,
    ).stdout
    if content != policy.read_bytes():
        raise SystemExit(f"signed content differs from {policy}")


def policies_in(*directories: str) -> tuple[Path, ...]:
    """List policy texts directly under the named policy directories."""
    return tuple(
        policy
        for directory in directories
        for policy in sorted((layout.build.POLICIES_DIR / directory).glob("*.pol"))
    )


@dataclass(frozen=True)
class SigningBatch:
    """Policies that share one CMS signing configuration."""

    policies: tuple[Path, ...]
    signer: signing.Identity
    certificates: tuple[Path, ...]
    trusted_certificate: Path


def shift(hexadecimal: str) -> str:
    """Return a same-length hexadecimal mismatch for negative cases.

    For example, ``shift("09af")`` returns ``"1ab0"``: each digit advances
    by one and ``f`` wraps to ``0``.
    """
    return "".join(
        HEX_DIGITS[(HEX_DIGITS.index(digit) + 1) % len(HEX_DIGITS)] for digit in hexadecimal
    )


def measurements() -> dict[str, str]:
    """Every placeholder and the <algorithm>:<hex> a policy should name."""
    table = {}
    for algorithm in hashes.DMVERITY_ALGORITHMS:
        root_hash = layout.build.root_hash(algorithm).read_text().strip()
        upper = algorithm.upper()
        table[f"@DMVERITY_ROOTHASH_{upper}@"] = f"{algorithm}:{root_hash}"
        table[f"@DMVERITY_OTHER_ROOTHASH_{upper}@"] = f"{algorithm}:{shift(root_hash)}"
    for algorithm in hashes.FSVERITY_ALGORITHMS:
        digest = layout.build.fsverity_digest(algorithm).read_text().strip()
        upper = algorithm.upper()
        table[f"@FSVERITY_DIGEST_{upper}@"] = f"{algorithm}:{digest}"
        table[f"@FSVERITY_OTHER_DIGEST_{upper}@"] = f"{algorithm}:{shift(digest)}"
    return table


def fill_in_measurements() -> None:
    replacements = measurements()
    for policy in layout.build.POLICIES_DIR.rglob("*.pol"):
        text = policy.read_text()
        for placeholder, value in replacements.items():
            text = text.replace(placeholder, value)
        policy.write_text(text)


def main() -> int:
    if not signing.BUILTIN.key.is_file() or not signing.BUILTIN.certificate.is_file():
        raise SystemExit("signing keys are missing; run prepare-keys.py")
    shutil.rmtree(layout.build.POLICIES_DIR, ignore_errors=True)
    shutil.copytree(layout.source.POLICIES_DIR, layout.build.POLICIES_DIR)
    fill_in_measurements()

    signing_batches = (
        SigningBatch(
            policies=(
                *sorted(layout.build.POLICIES_DIR.glob("*.pol")),
                *policies_in(
                    "boot",
                    "capability",
                    "dmverity",
                    "fsverity",
                    "policy",
                    "policy_text",
                ),
                layout.build.TAMPERED_POLICY_TEXT,
            ),
            signer=signing.BUILTIN,
            certificates=(),
            trusted_certificate=signing.BUILTIN.certificate,
        ),
        SigningBatch(
            policies=(layout.build.UNTRUSTED_POLICY_TEXT,),
            signer=signing.UNTRUSTED,
            certificates=(),
            trusted_certificate=signing.UNTRUSTED.certificate,
        ),
        SigningBatch(
            policies=(layout.build.SECONDARY_POLICY_TEXT,),
            signer=signing.SECONDARY,
            certificates=(),
            trusted_certificate=signing.INTERMEDIATE.certificate,
        ),
        SigningBatch(
            policies=(layout.build.PLATFORM_POLICY_TEXT,),
            signer=signing.SECUREBOOT,
            certificates=(),
            trusted_certificate=signing.SECUREBOOT.certificate,
        ),
        SigningBatch(
            policies=(layout.build.REVOKED_POLICY_TEXT,),
            signer=signing.REVOKED,
            certificates=(),
            trusted_certificate=signing.REVOKED.certificate,
        ),
    )
    for batch in signing_batches:
        for policy in batch.policies:
            sign(
                policy=policy,
                output=policy.with_suffix(".p7s"),
                signer=batch.signer,
                certificates=batch.certificates,
                trusted_certificate=batch.trusted_certificate,
            )

    policy_paths = {
        policy.with_suffix("")
        for policy in layout.build.POLICIES_DIR.rglob("*.pol")
    }
    signature_paths = {
        signature.with_suffix("")
        for signature in layout.build.POLICIES_DIR.rglob("*.p7s")
    }
    if policy_paths != signature_paths:
        missing = policy_paths - signature_paths
        unexpected = signature_paths - policy_paths
        details = [
            *(
                f"missing signature: {path.relative_to(layout.build.POLICIES_DIR)}"
                for path in sorted(missing)
            ),
            *(
                f"unexpected signature: {path.relative_to(layout.build.POLICIES_DIR)}"
                for path in sorted(unexpected)
            ),
        ]
        raise SystemExit("; ".join(details))

    layout.build.SIGNER_CERTIFICATES_DIR.mkdir(parents=True, exist_ok=True)
    intermediate = x509.load_pem_x509_certificate(
        signing.INTERMEDIATE.certificate.read_bytes()
    )
    layout.build.INTERMEDIATE_CERTIFICATE.write_bytes(
        intermediate.public_bytes(serialization.Encoding.DER)
    )

    print(f"    Prepared {len(policy_paths)} signed policies")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
