# SPDX-License-Identifier: GPL-2.0-only
"""Define signing identities and paths for the files generated by prepare-keys.py."""

from dataclasses import dataclass
from pathlib import Path

import layout


@dataclass(frozen=True)
class Identity:
    name: str

    @property
    def key(self) -> Path:
        return layout.build.KEYS_DIR / f"{self.name}-key.pem"

    @property
    def certificate(self) -> Path:
        return layout.build.KEYS_DIR / f"{self.name}-cert.pem"


BUILTIN = Identity("builtin")
INTERMEDIATE = Identity("intermediate")
SECONDARY = Identity("secondary")
REVOKED = Identity("revoked")
UNTRUSTED = Identity("untrusted")
SECUREBOOT = Identity("secureboot")
FSVERITY = Identity("fsverity")

# The kernel build wants one file holding both, so this one is not an identity
# in the sense above.
MODULE_SIGNING = layout.build.KEYS_DIR / "module-signing.pem"
