# SPDX-License-Identifier: GPL-2.0-only

[Content]
Packages=
        keyutils
        kmod
        python3
        util-linux

ExtraTrees=%D/initrd/anchor-fsverity.service:/usr/lib/systemd/system/anchor-fsverity.service
           %D/initrd/ipe-tests-boot-verified.service:/usr/lib/systemd/system/ipe-tests-boot-verified.service
           %D/initrd/boot-verified:/usr/lib/ipe-tests/boot-verified
           %D/../suite:/usr/lib/ipe-tests
           %D/../scripts/layout.py:/usr/lib/ipe-tests/layout.py
           %D/../scripts/hashes.py:/usr/lib/ipe-tests/hashes.py
           %D/../build/policies/boot/kmodule_boot_verified_allow.p7s:/usr/lib/ipe-tests/boot-verified-true.p7s
           %D/../build/policies/boot/kmodule_boot_verified_false_deny.p7s:/usr/lib/ipe-tests/boot-verified-false.p7s
           %D/../build/kernel-module/ipe_test.ko:/usr/lib/ipe-tests/ipe_test.ko
           %D/initrd/initrd.target.wants:/usr/lib/systemd/system/initrd.target.wants
           %D/../build/keys/fsverity-cert.der:/usr/lib/ipe/fsverity-cert.der
