# SPDX-License-Identifier: GPL-2.0-only

[Distribution]
Distribution=fedora
Release=43

[Output]
Format=disk
OutputDirectory=output
ImageId=ipe-tests

[Content]
Bootable=yes
Bootloader=uki
KernelModulesInitrd=no
Packages=
        systemd
        systemd-udev
        systemd-boot-unsigned
        coreutils
        util-linux
        python3

ExtraTrees=%D/systemd:/usr/lib/systemd/system
           %D/systemd-preset/95-ipe-tests.preset:/usr/lib/systemd/system-preset/95-ipe-tests.preset
           %D/../build/kernel-install:/

KernelCommandLine=root=dissect
                  systemd.verity=no
                  systemd.image_policy=root=signed:esp=unused:=absent
                  systemd.firstboot=no
                  systemd.volatile=state

RootPassword=hashed:

[Validation]
Verity=signed
VerityKey=%D/../build/keys/signing-key.pem
VerityCertificate=%D/../build/keys/signing-cert.pem
SecureBoot=yes
SecureBootKey=%D/../build/keys/secureboot-key.pem
SecureBootCertificate=%D/../build/keys/secureboot-cert.pem
SignExpectedPcr=no

[Runtime]
Firmware=uefi-secure-boot
FirmwareVariables=custom
RAM=2G
CPUs=2
KVM=auto
TPM=no

KernelCommandLineExtra=loglevel=7
