# SPDX-License-Identifier: GPL-2.0-only

[Content]
Packages=
        keyutils
        libseccomp
        kmod
        python3
        util-linux

ExtraTrees=%D/initrd/anchor-fsverity.service:/usr/lib/systemd/system/anchor-fsverity.service
           %D/initrd/ipe-tests-boot-verified.service:/usr/lib/systemd/system/ipe-tests-boot-verified.service
           %D/initrd/boot-verified.py:/usr/lib/ipe-tests/boot-verified.py
           %D/../suite:/usr/lib/ipe-tests
           %D/../scripts/layout.py:/usr/lib/ipe-tests/layout.py
           %D/../build/policies/boot/kmodule_boot_verified_allow.p7s:/usr/lib/ipe-tests/boot-verified-true.p7s
           %D/../build/policies/boot/kmodule_boot_verified_false_deny.p7s:/usr/lib/ipe-tests/boot-verified-false.p7s
           %D/../build/kernel-modules/ipe_test.ko:/usr/lib/ipe-tests/ipe_test.ko
           %D/../build/kernel-modules/ipe_test_policy_op.ko:/usr/lib/ipe-tests/ipe_test_policy_op.ko
           %D/../build/kernel-modules/ipe_test_x509.ko:/usr/lib/ipe-tests/ipe_test_x509.ko
           %D/../build/policies/boot/x509_cert_boot_verified_allow.p7s:/usr/lib/ipe-tests/x509-cert-boot-verified-true.p7s
           %D/../build/policies/boot/x509_cert_boot_verified_false_deny.p7s:/usr/lib/ipe-tests/x509-cert-boot-verified-false.p7s
           %D/../test-media/policy-op/ipe_test.policy:/usr/lib/ipe-tests/ipe_test.policy
           %D/../build/policies/boot/policy_op_boot_verified_allow.p7s:/usr/lib/ipe-tests/policy-op-boot-verified-true.p7s
           %D/../build/policies/boot/policy_op_boot_verified_false_deny.p7s:/usr/lib/ipe-tests/policy-op-boot-verified-false.p7s
           %D/../build/kexec/ipe_test.kernel:/usr/lib/ipe-tests/ipe_test.kernel
           %D/../build/kexec/ipe_test.cpio:/usr/lib/ipe-tests/ipe_test.cpio
           %D/../build/policies/boot/kexec_initramfs_boot_verified_allow.p7s:/usr/lib/ipe-tests/kexec-initramfs-boot-verified-true.p7s
           %D/../build/policies/boot/kexec_initramfs_boot_verified_false_deny.p7s:/usr/lib/ipe-tests/kexec-initramfs-boot-verified-false.p7s
           %D/../build/policies/boot/kexec_image_boot_verified_allow.p7s:/usr/lib/ipe-tests/kexec-image-boot-verified-true.p7s
           %D/../build/policies/boot/kexec_image_boot_verified_false_deny.p7s:/usr/lib/ipe-tests/kexec-image-boot-verified-false.p7s
           %D/../test-media/firmware/ipe_test.fw:/usr/lib/ipe-tests/ipe_test.fw
           %D/../build/policies/boot/firmware_boot_verified_allow.p7s:/usr/lib/ipe-tests/firmware-boot-verified-true.p7s
           %D/../build/policies/boot/firmware_boot_verified_false_deny.p7s:/usr/lib/ipe-tests/firmware-boot-verified-false.p7s
           %D/initrd/initrd.target.wants:/usr/lib/systemd/system/initrd.target.wants
           %D/../build/keys/fsverity-cert.der:/usr/lib/ipe/fsverity-cert.der

RemoveFiles=/usr/lib/ipe-tests/**/__pycache__
