# SPDX-License-Identifier: GPL-2.0-only

[Content]
Packages=
        keyutils

ExtraTrees=%D/initrd/anchor-fsverity.service:/usr/lib/systemd/system/anchor-fsverity.service
           %D/initrd/initrd.target.wants:/usr/lib/systemd/system/initrd.target.wants
           %D/../build/keys/fsverity-cert.der:/usr/lib/ipe-tests/fsverity-cert.der
